name: Deploy

on:
  push:
    branches:
      - delivery

jobs:
  test_build:
    name: Testing the Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Pnpm
        run: npm install pnpm@latest -g
      - name: Install dependencies
        run: pnpm install
      - name: Run build
        run: pnpm build
